// Copyright 2024 The Jumpstarter Authors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: jumpstarter/v1/rendezvous.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Rendezvous_Listen_FullMethodName = "/rendezvous.Rendezvous/Listen"
	Rendezvous_Dial_FullMethodName   = "/rendezvous.Rendezvous/Dial"
	Rendezvous_Stream_FullMethodName = "/rendezvous.Rendezvous/Stream"
)

// RendezvousClient is the client API for Rendezvous service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RendezvousClient interface {
	Listen(ctx context.Context, in *Request, opts ...grpc.CallOption) (Rendezvous_ListenClient, error)
	Dial(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Rendezvous_StreamClient, error)
}

type rendezvousClient struct {
	cc grpc.ClientConnInterface
}

func NewRendezvousClient(cc grpc.ClientConnInterface) RendezvousClient {
	return &rendezvousClient{cc}
}

func (c *rendezvousClient) Listen(ctx context.Context, in *Request, opts ...grpc.CallOption) (Rendezvous_ListenClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rendezvous_ServiceDesc.Streams[0], Rendezvous_Listen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &rendezvousListenClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rendezvous_ListenClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type rendezvousListenClient struct {
	grpc.ClientStream
}

func (x *rendezvousListenClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rendezvousClient) Dial(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Rendezvous_Dial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Rendezvous_StreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rendezvous_ServiceDesc.Streams[1], Rendezvous_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &rendezvousStreamClient{ClientStream: stream}
	return x, nil
}

type Rendezvous_StreamClient interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ClientStream
}

type rendezvousStreamClient struct {
	grpc.ClientStream
}

func (x *rendezvousStreamClient) Send(m *Frame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rendezvousStreamClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RendezvousServer is the server API for Rendezvous service.
// All implementations must embed UnimplementedRendezvousServer
// for forward compatibility
type RendezvousServer interface {
	Listen(*Request, Rendezvous_ListenServer) error
	Dial(context.Context, *Request) (*Response, error)
	Stream(Rendezvous_StreamServer) error
	mustEmbedUnimplementedRendezvousServer()
}

// UnimplementedRendezvousServer must be embedded to have forward compatible implementations.
type UnimplementedRendezvousServer struct {
}

func (UnimplementedRendezvousServer) Listen(*Request, Rendezvous_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedRendezvousServer) Dial(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedRendezvousServer) Stream(Rendezvous_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRendezvousServer) mustEmbedUnimplementedRendezvousServer() {}

// UnsafeRendezvousServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendezvousServer will
// result in compilation errors.
type UnsafeRendezvousServer interface {
	mustEmbedUnimplementedRendezvousServer()
}

func RegisterRendezvousServer(s grpc.ServiceRegistrar, srv RendezvousServer) {
	s.RegisterService(&Rendezvous_ServiceDesc, srv)
}

func _Rendezvous_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RendezvousServer).Listen(m, &rendezvousListenServer{ServerStream: stream})
}

type Rendezvous_ListenServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type rendezvousListenServer struct {
	grpc.ServerStream
}

func (x *rendezvousListenServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Rendezvous_Dial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).Dial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rendezvous_Dial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).Dial(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rendezvous_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RendezvousServer).Stream(&rendezvousStreamServer{ServerStream: stream})
}

type Rendezvous_StreamServer interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ServerStream
}

type rendezvousStreamServer struct {
	grpc.ServerStream
}

func (x *rendezvousStreamServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rendezvousStreamServer) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Rendezvous_ServiceDesc is the grpc.ServiceDesc for Rendezvous service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rendezvous_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rendezvous.Rendezvous",
	HandlerType: (*RendezvousServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dial",
			Handler:    _Rendezvous_Dial_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Rendezvous_Listen_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _Rendezvous_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "jumpstarter/v1/rendezvous.proto",
}
