# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jumpstarter/v1/rendezvous.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'jumpstarter/v1/rendezvous.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fjumpstarter/v1/rendezvous.proto\x12\nrendezvous\"!\n\x05\x46rame\x12\x18\n\x07payload\x18\x01 \x01(\x0cR\x07payload\"#\n\x07Request\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\"\"\n\x08Response\x12\x16\n\x06stream\x18\x01 \x01(\tR\x06stream2\xaa\x01\n\nRendezvous\x12\x35\n\x06Listen\x12\x13.rendezvous.Request\x1a\x14.rendezvous.Response0\x01\x12\x31\n\x04\x44ial\x12\x13.rendezvous.Request\x1a\x14.rendezvous.Response\x12\x32\n\x06Stream\x12\x11.rendezvous.Frame\x1a\x11.rendezvous.Frame(\x01\x30\x01\x42\xa9\x01\n\x0e\x63om.rendezvousB\x0fRendezvousProtoP\x01Z>github.com/jumpstarter-dev/jumpstarter-protocol/jumpstarter/v1\xa2\x02\x03RXX\xaa\x02\nRendezvous\xca\x02\nRendezvous\xe2\x02\x16Rendezvous\\GPBMetadata\xea\x02\nRendezvousb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jumpstarter.v1.rendezvous_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.rendezvousB\017RendezvousProtoP\001Z>github.com/jumpstarter-dev/jumpstarter-protocol/jumpstarter/v1\242\002\003RXX\252\002\nRendezvous\312\002\nRendezvous\342\002\026Rendezvous\\GPBMetadata\352\002\nRendezvous'
  _globals['_FRAME']._serialized_start=47
  _globals['_FRAME']._serialized_end=80
  _globals['_REQUEST']._serialized_start=82
  _globals['_REQUEST']._serialized_end=117
  _globals['_RESPONSE']._serialized_start=119
  _globals['_RESPONSE']._serialized_end=153
  _globals['_RENDEZVOUS']._serialized_start=156
  _globals['_RENDEZVOUS']._serialized_end=326
# @@protoc_insertion_point(module_scope)
