# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from jumpstarter.v1 import rendezvous_pb2 as jumpstarter_dot_v1_dot_rendezvous__pb2


class RendezvousStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listen = channel.unary_stream(
                '/rendezvous.Rendezvous/Listen',
                request_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Request.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Response.FromString,
                _registered_method=True)
        self.Dial = channel.unary_unary(
                '/rendezvous.Rendezvous/Dial',
                request_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Request.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Response.FromString,
                _registered_method=True)
        self.Stream = channel.stream_stream(
                '/rendezvous.Rendezvous/Stream',
                request_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.FromString,
                _registered_method=True)


class RendezvousServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RendezvousServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listen': grpc.unary_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Request.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Response.SerializeToString,
            ),
            'Dial': grpc.unary_unary_rpc_method_handler(
                    servicer.Dial,
                    request_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Request.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Response.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rendezvous.Rendezvous', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rendezvous.Rendezvous', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Rendezvous(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rendezvous.Rendezvous/Listen',
            jumpstarter_dot_v1_dot_rendezvous__pb2.Request.SerializeToString,
            jumpstarter_dot_v1_dot_rendezvous__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rendezvous.Rendezvous/Dial',
            jumpstarter_dot_v1_dot_rendezvous__pb2.Request.SerializeToString,
            jumpstarter_dot_v1_dot_rendezvous__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rendezvous.Rendezvous/Stream',
            jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.SerializeToString,
            jumpstarter_dot_v1_dot_rendezvous__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
